### ISSUE TITLE
One or more keys not valid after inputting three valid api keys

### ISSUE THREAD

**Issue by goopey7** [RuurdBijlsma/VueMusic#1]
I'm not able to get past the initial settings screen.

To make the spotify api keys, I went to https://developer.spotify.com/dashboard/applications
made a new app and pasted the id and secret to the first two lines.

For the youtube key I made a YouTube data api v3 key for public data for the third line.

after pasting these three the app doesn't seem to acknowledge and still says one or more keys not valid.

Get the same issue on windows and the [site](https://ruurd.dev/vuemusic/#/settings)

**Comment by RuurdBijlsma** [comment]
Just to confirm, have you formatted the api keys as follows:

```
asdf98asdfh9asjdf8ad890d08as8dds
jf0asd8fhahn0a8sdfhanhm0as89dd0f
gansdas0df8d-jdfbps9f87ashdfajhdflkjajs
```

The error of "one or more keys is not valid" happens when the following condition is not met:
```js
            spotifyId.length === 32 &&
            spotifySecret.length === 32 &&
            youtube.length === 39 &&
            youtube.indexOf('-') === 12
```

It's correct that you got the youtube data api v3, i have that one too. It might be that I got the checks for validness wrong. If any of your apis keys is of a different length than i check for above I'll update the code to include that

**Comment by goopey7** [comment]
My YouTube api key is pretty different. It has a '_' instead of a '-'. And it's at index 23 in the string. My key still has length 39.

**Comment by RuurdBijlsma** [comment]
I fixed the api key check thx for the report :) https://github.com/RuurdBijlsma/VueMusic/commit/5ea61f256c7809bc1a86793415044170d5d60aea

latest release has the update, web version doesnt yet
